// src/components/data-link/DashboardSummary.tsx

type DashboardSummaryProps = {
  dashboard: any;
};

function formatNumber(value: number | null | undefined) {
  if (value === null || value === undefined) return "0";
  return new Intl.NumberFormat("en-US").format(value);
}

export function DashboardSummary({ dashboard }: DashboardSummaryProps) {
  const { user, usage, limits, analytics, service } = dashboard;

  return (
    <section className="dl-dashboard-summary">
      <div>
        <div className="dl-section-heading">
          <h2>Account & limits</h2>
          <p>Your current plan and processing limits.</p>
        </div>

        <div className="dl-summary-grid dl-summary-grid-limits">
          <article className="dl-card">
            <span className="dl-card-label">Current plan</span>
            <strong>{user.plan}</strong>
            <small>{dashboard.billing?.billing_status || "Active access"}</small>
          </article>

          <article className="dl-card">
            <span className="dl-card-label">Files used</span>
            <strong>
              {usage.files_processed_this_month} / {limits.files_per_month}
            </strong>
            <small>{usage.usage_percentage}% of monthly limit</small>
          </article>

          <article className="dl-card">
            <span className="dl-card-label">Max file size</span>
            <strong>{limits.max_file_size_mb} MB</strong>
            <small>Per file</small>
          </article>

          <article className="dl-card">
            <span className="dl-card-label">Max records</span>
            <strong>{formatNumber(limits.max_records_per_file)}</strong>
            <small>Per file</small>
          </article>

          <article className="dl-card">
            <span className="dl-card-label">Service</span>
            <strong className="dl-status-text">{service.status}</strong>
            <small>Data_Link API</small>
          </article>
        </div>
      </div>

      <div>
        <div className="dl-section-heading">
          <h2>Processing impact</h2>
          <p>Measured value generated by your processed datasets.</p>
        </div>

        <div className="dl-summary-grid dl-summary-grid-impact">
          <article className="dl-card dl-card-accent">
            <span className="dl-card-label">Records processed</span>
            <strong>{formatNumber(analytics.total_records_processed)}</strong>
            <small>Total analyzed records</small>
          </article>

          <article className="dl-card dl-card-accent">
            <span className="dl-card-label">Duplicates removed</span>
            <strong>{formatNumber(analytics.duplicates_removed)}</strong>
            <small>Cleaned automatically</small>
          </article>

          <article className="dl-card dl-card-accent">
            <span className="dl-card-label">Records kept</span>
            <strong>{formatNumber(analytics.records_kept)}</strong>
            <small>Final clean records</small>
          </article>

          <article className="dl-card dl-card-accent dl-impact-main">
            <span className="dl-card-label">Avg. reduction</span>
            <strong>{analytics.average_reduction_percentage}%</strong>
            <small>{analytics.completed_jobs} completed job(s)</small>

            <div className="dl-impact-bar">
              <span
                style={{
                  width: `${Math.min(
                    analytics.average_reduction_percentage || 0,
                    100
                  )}%`,
                }}
              />
            </div>
          </article>
        </div>
      </div>
    </section>
  );
}